<?php
/**
 * @file hsc.module
 * Hearthstone cards management.
 */


/**
 * Implements hook_action_info().
 */
function hsc_action_info() {
  return array(
    'hsc_import_from_feed' => array(
      'type' => 'node',
      'label' => t('Import from this feed'),
      'behavior' => 'import_from_feed',
      'configurable' => TRUE,
      'vbo_configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}


/**
 * Implements hook_form_alter().
 */
function hsc_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'card_feed_node_form') {

    //$form['#cache'] = FALSE; // IMPORTANT!! to avoid the "Invalid form POST data" error.

    // Get form language.
    $lang = $form['field_card_code']['#language'];

    // Add ajax on card code field.
    $form['field_card_code'][$lang][0]['value']['#ajax'] = array(
      'callback' => '_hsc_import_ajax_card_code_callback',
      'wrapper' => 'card-code-preview',
      'effect' => 'fade',
    );

    // Get default card code value, if any.
    if (!empty($form_state['values']['field_card_code'][$lang][0]['value'])) {
      $default_value = $form_state['values']['field_card_code'][$lang][0]['value'];
    }
    elseif (!empty($form['field_card_code'][$lang][0]['value']['#default_value'])) {
      $default_value = $form['field_card_code'][$lang][0]['value']['#default_value'];
    }
    else {
      $default_value = '';
    }

    // Create preview.
    $form['card_code_preview'] = array(
      '#type' => 'container',
      '#weight' => $form['field_card_code']['#weight'] + 1,
      '#access' => TRUE,
      '#prefix' => '<div id="card-code-preview">',
      '#suffix' => '</div>',
    );
    if (!empty($default_value)) {
      $url = 'http://wow.zamimg.com/images/hearthstone/cards/' . $default_value . '/original/EX1_116.png';
      $form['card_code_preview'][$lang][0]['value'] = array(
        '#type' => 'item',
        '#theme' => 'link',
        '#text' => t('Preview picture'),
        '#path' => $url,
        '#options' => array(
          'attributes' => array('target' => '_blank'),
          'html' => FALSE,
        ),

      );
    }
    else {
      $form['card_code_preview'][$lang][0]['value'] = array(
        '#type' => 'item',
        '#markup' => '',
      );
    }

    // Update fields weight.
    foreach (element_children($form) as $field_name) {
      $element =& $form[$field_name];
      if (($field_name != 'field_card_code') && ($field_name != 'card_code_preview') && isset($element['#weight']) && ($element['#weight'] >= $form['card_code_preview']['#weight'])) {
        $element['#weight'] += 1;
      }
    }
  }
}


/**
 * Ajax callback.
 */
function _hsc_import_ajax_card_code_callback($form, $form_state) {
  return $form['card_code_preview'];
}


/**
 * Implements hook_action_form().
 */
function  hsc_import_from_feed_form($settings, &$form_state) {
	global $language;
	
	$form = array();
	$options = array('all' => t('All')) + locale_language_list();
	$form['language'] = array(
		'#type' => 'select',
	  '#title' => t('Choose import language:'),
	  '#options' => $options,
		'#default_value' => $language->language,
	);
	$form['collectible'] = array(
		'#type' => 'radios',
		'#title' => t('Collectible only?'),
		'#options' => array(t('No'), t('Yes')),
		'#default_value' => 1,
	);
	return $form;
}


/**
 * Implements hook_action_form_submit().
 */
function hsc_import_from_feed_submit($form, $form_state) {
	$return = array();
	
	$languages = array();
	if ($form_state['values']['language'] == 'all') {
	  foreach (locale_language_list() as $lang => $label) {
	    $languages[] = $lang;
	  }
	}
	else {
	  $languages[] = $form_state['values']['language'];
	}
	
	$return['hsc_import_settings'] = array(
	  'languages' => $languages, 
	  'collectible' => $form_state['values']['collectible'],
	);
	return $return; // Note, return value here must be an array.
}


/**
 * ACTION!
 */
function hsc_import_from_feed(&$node, $context) {
  $operations = array();
  
  $languages = $context['hsc_import_settings']['languages'];
  foreach ($languages as $language) {
    $feed_url = field_get_items('node', $node, 'field_url', $language);
    if ($feed_url !== FALSE) {
      $data_json = file_get_contents($feed_url[0]['value']);
      $data = json_decode($data_json);
      foreach ($data as $card) {
      	if (!($context['hsc_import_settings']['collectible']) || (($context['hsc_import_settings']['collectible']) && isset($card->collectible) && ($card->collectible == 1)))
        	$operations[] = array('hsc_import_batch_process', array($card, $node, $language));
      }
    }
  }
  
  if (!empty($operations)) {
    $batch = array(
      'title' => 'Import',
      'operations' => $operations,
      'finished' => 'hsc_import_batch_finished',
    );
    batch_set($batch);
    // Let's assume import worked well...
    $node->field_last_import[LANGUAGE_NONE][0]['value'] = REQUEST_TIME;
    node_save($node);
  }
}


/**
 * Helper function.
 */
function hsc_import_batch_process($card, $feed, $language, &$context) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node');
  $query->entityCondition('bundle', 'card');
  $query->propertyCondition('language', $language, '=');
  $query->fieldCondition('field_id', 'value', $card->id, '=');
  $query->range(0, 1);
  $result = $query->execute();
  $card_name = empty($card->name) ? $card->id : $card->name;
  $message = (isset($result['node']) ? 'Updating ' : 'Importing ') . '%card_name [%feed_name / %language].';
  $context['message'] = t($message, array('%card_name' => $card_name, '%feed_name' => $feed->title, '%language' => strtoupper($language)));
  hsc_import_batch_process_import_card($card, $feed, $language);
  $context['results'][] = check_plain($card_name) . ' [' . check_plain($card->id) . '].';
}


/**
 * Helper function.
 */
function hsc_import_batch_process_import_card($card, $feed, $language) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node');
  $query->entityCondition('bundle', 'card');
  $query->propertyCondition('language', $language, '=');
  $query->fieldCondition('field_id', 'value', $card->id, '=');
  $query->range(0, 1);
  $results = $query->execute();
  if (isset($results['node'])) {
    $result = array_shift($results['node']);
    $node = node_load($result->nid);
  }
  else {
    $node = new stdClass();
    $node->type = 'card';
    $node->language = $language;
    $node->is_new = TRUE;
    node_object_prepare($node);
    
    // Seek for translations
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node');
    $query->entityCondition('bundle', 'card');
    $query->propertyCondition('language', $language, '!=');
    $query->fieldCondition('field_id', 'value', $card->id, '=');
    $query->propertyOrderBy('created', 'ASC');
    $query->range(0, 1);
    $results = $query->execute();
    if (isset($results['node'])) {
    	$result = array_shift($results['node']);
    	$source = node_load($result->nid);
    	if ($source->tnid) {
    		$node->tnid = $source->tnid;
    	}
    	else {
    		$node->tnid = $source->nid;
    		$source->tnid = $source->nid;
    		node_save($source);
    	}
    }
  }

  // Associate source feed
  $node->field_feed[LANGUAGE_NONE][0]['target_id'] = $feed->nid;
  
  // Other fields
  foreach ($card as $property => $value) {
    switch ($property) {
      // Title
      case 'name':
        $node->title = empty($value) ? $card->id : $value;
        break;
      // Numeric & boolean values
      case 'cost':
      case 'attack':
      case 'health':
      case 'durability':
      case 'collectible':
      case 'elite':
        $node->{'field_' . $property}[LANGUAGE_NONE][0]['value'] = (int) $value;
        break;
      // Taxonomies
      case 'type':
      case 'rarity':
      case 'faction':
      case 'race':
      case 'playerClass':
        $property = strtolower($property);
        $terms = taxonomy_get_term_by_name($value, $property);
        if (!empty($terms)) {
          $term = array_shift($terms);
        }
        else {
          $vocab = taxonomy_vocabulary_machine_name_load($property);

          $term = new stdClass();
          $term->name = $value;
          $term->vid = $vocab->vid;
          $term->language = 'en';
          taxonomy_term_save($term);
        }
        $node->{'field_' . $property}[LANGUAGE_NONE][0]['target_id'] = $term->tid;
        break;
      // Multiple taxonomies
      case 'mechanics':
        $property = strtolower($property);
        $cpt = 0;
        foreach ($value as $val) {
          $terms = taxonomy_get_term_by_name($val, $property);
          if (!empty($terms)) {
            $term = array_shift($terms);
          }
          else {
            $vocab = taxonomy_vocabulary_machine_name_load($property);

            $term = new stdClass();
            $term->name = $val;
            $term->vid = $vocab->vid;
            $term->language = 'en';
            taxonomy_term_save($term);
          }
          $node->{'field_' . $property}[LANGUAGE_NONE][$cpt++]['target_id'] = $term->tid;
        }
        break;
      // Default: text values
      default:
        $property = strtolower($property);
        $node->{'field_' . $property}[LANGUAGE_NONE][0]['value'] = $value;
        break;
    }
  }

  $code_carte = field_get_items('node', $feed, 'field_card_code', $language);
  if ($code_carte !== FALSE) {
	  // Card picture
	  $directory = "public://cards/$language/original";
  	if (file_prepare_directory($directory, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
		  $url = 'http://wow.zamimg.com/images/hearthstone/cards/' . $code_carte[0]['value'] . '/original/' . $card->id . '.png';
		  $file_headers = @get_headers($url);
		  if (($file_headers[0] == 'HTTP/1.0 200 OK') && ($fic_picture = system_retrieve_file($url, $directory, TRUE, FILE_EXISTS_RENAME))) {
		    $node->field_picture[LANGUAGE_NONE][0] = (array) $fic_picture;
		  }
  	}
	
	  // Golden card picture
	  $directory = "public://cards/$language/animated";
	  if (file_prepare_directory($directory, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
		  $url = 'http://wow.zamimg.com/images/hearthstone/cards/' . $code_carte[0]['value'] . '/animated/' . $card->id . '_premium.gif';
		  $file_headers = @get_headers($url);
		  if (($file_headers[0] == 'HTTP/1.0 200 OK') && ($fic_picturegold = system_retrieve_file($url, $directory, TRUE, FILE_EXISTS_RENAME))) {
		    $node->field_picturegold[LANGUAGE_NONE][0] = (array) $fic_picturegold;
		  }
	  }
  }
  
  // Sauvegarde
  $node = node_submit($node);
  node_save($node);
}


/**
 * Helper function.
 */
function hsc_import_batch_finished($success, $results, $operations) {
  // The 'success' parameter means no fatal PHP errors were detected. All
  // other error management should be handled using 'results'.
  if ($success) {
    $message = format_plural(count($results), 'One card was successfully imported.', '@count cards were successfully imported.');
  }
  else {
    $message = t('An error has occured.');
  }
  drupal_set_message($message);
}


/**
 * Implements hook_views_api().
 */
function hsc_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'hsc'),
    'template path' => drupal_get_path('module', 'hsc') . '/templates',
  );
}
